framework:
    exceptions:
        Cicada\Storefront\Framework\Captcha\Exception\CaptchaInvalidException:
            log_level: notice
        Cicada\Storefront\Theme\Exception\ThemeException:
            log_level: notice
        Cicada\Storefront\Theme\Exception\ThemeAssignmentException:
            log_level: notice
